// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  testimonial: dynamic(() => import("./Testimonials")),
  text_with_slice: dynamic(() => import("./TextWithImage")),
};
